name: create-repo-issue-output-test
on:
  push:
  
jobs:

  msg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Simple demo for reusable workflow"
    
  create-new-issue:
    uses: labrats-work/actions.common/.github/workflows/create-repo-issue-output.yml@main
    secrets: inherit
    with:
      title: "Test issue"
      body: "Test body"

  
  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: echo ${{ needs.create-new-issue.outputs.issue-num }}
